### ISSUE TITLE
Aggiunta collegamento a stella

### ISSUE THREAD

**Issue by Alberto756** [Manulinkraft/progetto-esame#10]
Il motore elettrico è stato, da noi, alimentato mediante un collegamento a stella. In questo tipo di collegamento, si collega ogni fase ai tre capi di tre avvolgimenti e gli altri tre capi si collegano tra loro per formare il centro stella. Il sistema trifase è solitamente utilizzato per potenze elevate,superiori ai 6 kilowatt. La trifase è utilizzata anche per le utenze domestiche, solo nel caso in cui sia presente un notevole consumo di energia elettrica. Nelle applicazioni industriali é preferibile usare un collegamento a stella-triangolo con i relativi dispositivi di sicurezza. Il contatore di energia è un dispositivo che effettua uno sganciamento nel caso in cui ci sia un eccessivo assorbimento di corrente. Sono presenti, inoltre, dei relè termici che che hanno la funzione di proteggere il sistema al verificarsi di un sovraccarico di corrente elettrica. Le principali cause di questo tipo di malfunzionamento sono dettate da: tempi di avviamento troppo lunghi, variazioni elevate della tensione e della frequenza di rete, funzionamento in bifase per mancanza di una fase,blocco del rotore e coppia resistente troppo elevata in relazione al tipo di motore. Questi tipi di dispositivo non proteggono però dal cortocircuito ed è per quest'ultimo motivo che vengono impiegati i relè magnetici e i fusibili. A seconda della richiesta, viene impiegato uno tra i due sistemi. Per quanto riguarda la caratteristica di intervento,

**Comment by Alberto756** [comment]
Per quanto riguarda la caratteristica di intervento, i fusibili sono dispositivi a tempo inverso, cioè, per intervenire devono accumulare una certa quantità di energia termica  al fine di riscaldare l'elemento conduttore fino alla completa fusione ed evaporazione.D'altro canto,il relè magnetico possiede un tempo di intervento indipendente dal valore della corrente, purché essa sia superiore al valore che influenza il campo magnetico. La sua caratteristica di intervento è a scatto instantaneo e, seppur di poco, è più reattivo di un generico fusibile.

**Comment by CampelloManuel** [comment]
fin qua tutto aggiunto
* [x] ok

**Comment by CampelloManuel** [comment]
ok fatto 👍
