### ISSUE TITLE
HEATING SYSTEMS

### ISSUE THREAD

**Issue by Alberto756** [Manulinkraft/progetto-esame#12]
The scheme of a district scheme comprises a network of insulated pipes used to deliver heat from the point of generation to the end user. Discrict heating has a positive influence on climate change. It offers substancial potential to increase renewables-based heating particularly in urban areas. It also provides for considerable savings of fossil primary sources such as oil and gas. Another important aspect consists of that district heating doesn't allow the use of unused heat from traditional electricity generation, but can also use bio fuels,waste and large heat pumps to generate in an environmentally sustainable way.

**Comment by Alberto756** [comment]
Considering the central heating system, there is a clear connection because it provides heat to whole apparatus.

**Comment by CampelloManuel** [comment]
tutto copiato
