### ISSUE TITLE
Aggiungi 

### ISSUE THREAD

**Issue by Alberto756** [Manulinkraft/progetto-esame#5]
Il progetto in questione consiste nella realizzazione di un sistema di regolazione per il cogeneratore. Noi volevamo produrre un sistema, completo di sonde per la lettura dei dati, di una regolazione degli attuatori e di una modalità di visualizzazione dei valori misurati. Siamo partiti da un cogeneratore basato su un motore a due tempi, marcato Piaggio, corredato da uno scambiatore di fumi collegato al bollitore. Inizialmente, è stata necessaria una fase propedeutica al lavoro che consisteva nella consultazione di materiale documentativo pre- esistente fornitoci dai costruttori dei vari componenti. In seguito, abbiamo effettuato un rilievo del sistema cogeneratore con i relativi elementi. Questo disegno provvisorio è stato poi realizzato con i simboli unificati e convertito in formato digitale con Autocad. Successivamente a ciò, è seguita una fase di “brainstorming” sulle idee possibili e sensate. Dopo aver concluso questa parte iniziale, abbiamo compiuto alcune prove con la piattaforma elettronica Arduino. Sono stati testati alcuni accessori presenti nel kit di Arduino, come il telecomando, il display e il sensore di prossimità, per capire, non solo il loro funzionamento, ma anche cosa si sarebbe potuto aggiungere al progetto di utile ed efficace. Dopo l’osservazione di questi componenti elettronici, è risultato necessario effettuare un ulteriore analisi relativo al funzionamento sia del sistema idraulico che di quello elettrico. Per ciò che riguarda le mansioni svolte, noi abbiamo compiuto delle prove inerenti all’accensione del motore termico. Dopo la prova iniziale, ci siamo venuti a scontrare con il mancato avviamento del motore. É per quest’ultimo motivo che sono state necessarie altre prove per individuare i problemi del motore termico. Come prima cosa, abbiamo effettuato la pulizia degli ugelli del carburatore e cambiato le relative guarnizioni, che non erano nella miglior condizione. In risposta al fatto che ,durante l’accensione, il combustibile non veniva aspirato e di conseguenza il motore non andava in moto, abbiamo deciso di sostituire il dispositivo che aspirava l’aria in modo automatico con un filo per l’aria manuale. Nonostante ciò, il motore a due tempi non si è acceso a causa di un grave difetto strutturale. Per far sì che l’impianto di cogenerazione sia collegato, in maniera più comoda possibile, sia alla rete di distribuzione sia alla rete elettrica è stato necessario effettuare una derivazione dalla rete elettrica monofase principale. Conseguentemente, abbiamo proceduto all’installazione del motore elettrico per sopperire al mancato funzionamento del motore termico. Il motore elettrico è stato alimentato mediante, un collegamento a stella, alla presa trifase. È stato dotato, inoltre, di un sopporto per regolarlo in lunghezza e altezza e per limitare le vibrazioni provocate dal motore stesso. Per ciò che riguarda il cablaggio, abbiamo effettuato vari collegamenti intercorsi da alcuni morsetti. È stato realizzato il ponte che mette in relazione i cavi uscenti dall’alternatore con quelli del relè. Successivamente, abbiamo installato una cassetta elettrica con all’interno alcuni relè, che collegati opportunamente, permettono la regolazione del circolatore. Abbiamo messo in stretto contatto sul quadro anche, mediante un cavo Ethernet, il servomotore e la valvola. Dopo il cablaggio di tutti i collegamenti necessari, abbiamo realizzato un programma apposito con IDEARDUINO, sfruttando anche una piattaforma di simulazione.

**Comment by CampelloManuel** [comment]
bello!

**Comment by CampelloManuel** [comment]
apposto
