### ISSUE TITLE
Aggiunta

### ISSUE THREAD

**Issue by Alberto756** [Manulinkraft/progetto-esame#6]
Gli obiettivi tecnici che ci siamo preposti sono moltecipli. Il nostro scopo principale consisteva nella realizzazione di un sistema di regolazione. Quest’ultimo avrebbe dovuto controllare l’accelerazione del motore a seconda della velocità di rotazione (numero di giri).Il regolatore elettronico, mediante lo spegnimento o l’apertura della pompa, avrebbe dovuto regolare l’entrata di acqua nel bollitore e la conseguente temperatura all’interno di esso. Il dispositivo inoltre avrebbe dovuto anche controllare la temperatura di surriscaldamento e raffreddamento del motore termico. A causa del mancato funzionamento del motore termico, è stata necessaria l’installazione di un motore termico che ha portato ad una diversa realizzazione degli obiettivi precedentemente elencati. Un’altra opportunità, che si era venuta a presentare, riguardava l’applicazione di un display. Esso avrebbe dovuto visualizzare i dati provenienti, per esempio, dalla lettura dei giri. Non è stato possibile però collegarlo a causa degli eccessivi collegamenti richiesti. Per rimediare al cambio di regolazione, abbiamo dovuto effettuare dei nuovi disegni contenenti gli schemi idraulici ed elettrici(comando e potenza) con la relativa documentazione descrittiva. 
2.3	–Attrezzatura – p. 6 strumenti e materiali
Per la realizzazione dell’impianto di cogenerazione e per il cablaggio dei cavi elettrici, è stato necessario l’utilizzo di alcuni strumenti e materiali. Durante il collegamento dei fili elettrici ai relativi morsetti, abbiamo usato i tipici strumenti da elettricisti(pinze,…). Per la costruzione dei supporti per le pulegge e per il tubo dei gas di scarico ,invece, è stato doveroso l’utilizzo del tornio e dei relativi utensili. La realizzazione del supporto per il motore elettrico ha richiesto inoltre l’impiego della saldatrice e della fresatrice verticale
2.4	– Prerequisiti – p. 6
La conoscenza di alcuni concetti teorici è necessaria come pre-requisito, in maniera più specifica essi riguardano la cogenerazione, il motore elettrico asincrono trifase e i regolatori programmabili, come ad esempio Arduino. Non bastano solamente le nozioni teoriche ma è necessario possedere anche delle abilità pratiche riferite all’esperienza avente con le macchine utensili e con l’ambiente dell’elettronica.

**Comment by CampelloManuel** [comment]
aggiunto
