### ISSUE TITLE
Aggiunta

### ISSUE THREAD

**Issue by Alberto756** [Manulinkraft/progetto-esame#8]
Lo sviluppo del nostro progetto è avvenuto soprattutto a scuola durante l’orario scolastico e, alcune volte, durante l’orario pomeridiano. Non è stato possibile lavorare molto a casa in quanto il cogeneratore era istallato in maniera fissa a scuola. Abbiamo effettuato però delle prove di programmazione su una piattaforma di simulazione digitale. Il lavoro è stato svolto, nella maggior parte dei casi, in coppia. Durante le lavorazioni al tornio e il cablaggio dei cavi, il lavoro è stato suddiviso per essere più veloci ed efficienti. 
2.7 - Dati raccolti calcoli e risultati
I risultati finali sono rappresentati dal fatto di essere stati in grado di installare il motore elettrico con il relativo supporto e di avere creato la presa elettrica sia per l’allacciamento monofase che trifase. Il nostro lavoro ha portato anche alla creazione di una rete dove abbiamo situato il quadro elettrico. Il cablaggio della rete di regolazione ci ha permesso, inoltre, di leggere il numero di giri mediante la piattaforma Arduino.

**Comment by CampelloManuel** [comment]
aggiunto
